export const demoStudentExperience = {
  steps: [
    {
      title: "Preview the enrolled home",
      description: "Start with a sample student dashboard that shows classes, homework, reports, and support in one place.",
    },
    {
      title: "Explore each module",
      description: "Open realistic preview pages for schedule, homework, attendance, payments, tournaments, and more.",
    },
    {
      title: "Try live practice tools",
      description: "Use the available training tools to experience the learning environment today.",
    },
    {
      title: "Know what comes next",
      description: "See the information parents and students can expect after enrollment, with demo data clearly marked.",
    },
  ],
  stats: {
    upcomingClasses: 3,
    homework: 4,
    attendance: "96%",
    credits: 12,
    enrolledPreview: 11,
  },
  modules: [
    {
      slug: "upcoming-schedule",
      title: "Upcoming Schedule",
      summary: "Upcoming live classes, coach, topic, time, and join status.",
      metric: "3 classes",
      cta: "View Schedule",
      icon: "calendar",
    },
    {
      slug: "homework-view",
      title: "Homework View",
      summary: "Assignments, deadlines, submission states, score previews, and feedback.",
      metric: "4 tasks",
      cta: "View Homework",
      icon: "homework",
    },
    {
      slug: "attendance-view",
      title: "Attendance View",
      summary: "Attendance percentage, punctuality, class-wise status, and monthly summary.",
      metric: "96%",
      cta: "View Attendance",
      icon: "attendance",
    },
    {
      slug: "calendar-view",
      title: "Calendar View",
      summary: "Classes, homework due dates, tournament reminders, and review sessions.",
      metric: "6 events",
      cta: "Open Calendar",
      icon: "calendar",
    },
    {
      slug: "progress-report",
      title: "Progress Report",
      summary: "Learning progress, strengths, milestones, accuracy, and next focus areas.",
      metric: "82%",
      cta: "View Report",
      icon: "progress",
    },
    {
      slug: "leader-board",
      title: "Leader Board",
      summary: "XP ranking, coins, badges, monthly movement, and friendly competition.",
      metric: "#12",
      cta: "View Board",
      icon: "leaderboard",
    },
    {
      slug: "tournaments",
      title: "Tournaments",
      summary: "Upcoming events, formats, registration status, and sample pairings.",
      metric: "2 open",
      cta: "View Events",
      icon: "trophy",
    },
    {
      slug: "credits-and-payments",
      title: "Credits & Payments",
      summary: "Class credit balance, package validity, invoices, and payment history.",
      metric: "12 credits",
      cta: "View Credits",
      icon: "wallet",
    },
    {
      slug: "ask-coach",
      title: "Ask Coach",
      summary: "Questions, coach replies, guidance threads, and learning follow-ups.",
      metric: "2 replies",
      cta: "Ask a Question",
      icon: "message",
    },
    {
      slug: "class-history",
      title: "Class History",
      summary: "Completed classes, topics covered, homework links, and coach summaries.",
      metric: "5 classes",
      cta: "View History",
      icon: "history",
    },
    {
      slug: "certificates",
      title: "Certificates",
      summary: "Unlocked certificates, earned badges, milestones, and award dates.",
      metric: "2 earned",
      cta: "View Certificates",
      icon: "certificate",
    },
  ],
  upcomingClasses: [
    {
      title: "Opening Principles Lab",
      coach: "Coach Arjun",
      dateLabel: "Fri, 11 Jul",
      timeLabel: "5:30 PM",
      format: "Live classroom with puzzles",
      joinLabel: "Join opens 10 minutes before class",
      status: "Demo Preview",
    },
    {
      title: "Tactics Builder",
      coach: "Coach Meera",
      dateLabel: "Sun, 13 Jul",
      timeLabel: "10:00 AM",
      format: "Interactive lesson and quiz",
      joinLabel: "Coach notes attached",
      status: "Demo Preview",
    },
    {
      title: "Endgame Essentials",
      coach: "Coach Rahul",
      dateLabel: "Tue, 15 Jul",
      timeLabel: "6:15 PM",
      format: "Classroom with recap worksheet",
      joinLabel: "Homework review included",
      status: "Demo Preview",
    },
  ],
  homework: [
    {
      title: "Pin and Fork Puzzle Sheet",
      dueLabel: "Due after Sunday class",
      items: 12,
      status: "Assigned",
      score: "8/10 sample score",
      accuracy: "80%",
    },
    {
      title: "Mini Opening Review",
      dueLabel: "Due in 2 days",
      items: 6,
      status: "Submitted",
      score: "Teacher feedback ready",
      accuracy: "92%",
    },
    {
      title: "Mate in Two Challenge",
      dueLabel: "Due this week",
      items: 10,
      status: "Assigned",
      score: "XP reward on completion",
      accuracy: "-",
    },
    {
      title: "Endgame Basics",
      dueLabel: "Due next Friday",
      items: 8,
      status: "Not started",
      score: "Coach will review",
      accuracy: "-",
    },
  ],
  attendance: [
    { label: "Classes attended", value: "24 / 25" },
    { label: "On-time rate", value: "92%" },
    { label: "Average class rating", value: "4.8 / 5" },
    { label: "This month", value: "13 / 15" },
  ],
  progress: [
    { label: "Homework completion", value: "88%" },
    { label: "Tactics accuracy", value: "81%" },
    { label: "Current streak", value: "9 days" },
    { label: "Next milestone", value: "Reach 1200 rating" },
    { label: "Strong area", value: "Tactics and opening principles" },
    { label: "Coach note", value: "Ready for intermediate puzzles" },
  ],
  leaderboard: [
    { rank: "1", name: "Aanya S.", detail: "1,280 XP", coins: 8 },
    { rank: "2", name: "Vihaan R.", detail: "1,130 XP", coins: 8 },
    { rank: "3", name: "Advait M.", detail: "980 XP", coins: 5 },
    { rank: "12", name: "Your Rank", detail: "620 XP", coins: 3 },
  ],
  tournaments: [
    {
      title: "Envision Saturday Arena",
      detail: "Sat, 17 May - 4:00 PM",
      status: "Registration open",
      format: "Rapid 10+5",
    },
    {
      title: "Beginner Swiss Cup",
      detail: "Sun, 25 May - 10:00 AM",
      status: "Register",
      format: "4 rounds",
    },
  ],
  credits: [
    { label: "Plan", value: "Trial Pack" },
    { label: "Credits left", value: "12 classes" },
    { label: "Package valid till", value: "20 Jun 2026" },
    { label: "Last invoice", value: "Paid online" },
    { label: "Per-class deduction", value: "1 credit" },
    { label: "Receipts", value: "Available after payment" },
  ],
  askCoach: [
    {
      title: "How do I defend against Scholar's Mate?",
      reply: "Coach Meera shared a short defensive checklist and practice position.",
    },
    {
      title: "Which opening is best for beginners?",
      reply: "Coach Arjun recommended simple development plans before memorizing lines.",
    },
  ],
  calendar: [
    { day: "May 13", time: "5:30 PM", type: "Class", title: "Tactics Class" },
    { day: "May 17", time: "10:00 AM", type: "Review", title: "Tournament Review" },
    { day: "May 19", time: "5:00 PM", type: "Homework", title: "Mate in Two due" },
    { day: "May 21", time: "6:00 PM", type: "Class", title: "Rapid Arena Simulation" },
    { day: "May 25", time: "10:00 AM", type: "Tournament", title: "Beginner Swiss Cup" },
    { day: "May 30", time: "6:30 PM", type: "Report", title: "Monthly progress report" },
  ],
  classHistory: [
    {
      title: "King Hunt and Checkmates",
      detail: "Completed - 9 May 2025",
    },
    {
      title: "Positional Play Basics",
      detail: "Completed - 7 May 2025",
    },
    {
      title: "Opening Traps to Avoid",
      detail: "Completed - PGN study shared",
    },
    {
      title: "Endgame King Activity",
      detail: "Completed - Position drills practiced",
    },
    {
      title: "Rapid Game Review",
      detail: "Completed - Mistake pattern noted",
    },
  ],
  certificates: [
    {
      title: "Beginner Tactics Spiral",
      detail: "Unlocked - 8 May 2025",
    },
    {
      title: "Attendance Champion",
      detail: "Awarded - 1 May 2025",
    },
  ],
} as const;
