export type PortalRole = "student" | "instructor" | "admin" | "sub-admin";
export type FeatureStatus = "enabled" | "disabled" | "testing" | "coming_soon";

export type FeaturePermission = {
  id: string;
  label: string;
  critical?: boolean;
};

export type FeatureDefinition = {
  key: string;
  label: string;
  category: string;
  description: string;
  routes: string[];
  apiPrefixes?: string[];
  permissions: FeaturePermission[];
  defaultStatus?: FeatureStatus;
  defaultRolePermissions?: Partial<Record<PortalRole, string[]>>;
};

export const PORTAL_ROLES: PortalRole[] = ["student", "instructor", "admin", "sub-admin"];

const view = { id: "view", label: "View" };
const create = { id: "create", label: "Create" };
const edit = { id: "edit", label: "Edit" };
const del = { id: "delete", label: "Delete", critical: true };
const manage = { id: "manage", label: "Manage", critical: true };
const approve = { id: "approve", label: "Approve", critical: true };
const assign = { id: "assign", label: "Assign" };
const exportRecords = { id: "export", label: "Export" };
const share = { id: "share", label: "Share" };
const full = { id: "full", label: "Full Access", critical: true };

const all = (...items: FeaturePermission[]) => items.map((item) => item.id);

export const FEATURE_DEFINITIONS: FeatureDefinition[] = [
  {
    key: "dashboard",
    label: "Dashboard",
    category: "Learning",
    description: "Home dashboard, summaries, shortcuts, and portal entry points.",
    routes: ["/dashboard"],
    permissions: [view],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view"], instructor: ["view"], admin: ["view"] },
  },
  {
    key: "classrooms",
    label: "Classrooms",
    category: "Classroom",
    description: "Classes, classroom details, live sessions, summaries, and scheduling records.",
    routes: ["/classrooms", "/instructor/classrooms"],
    apiPrefixes: ["/api/classrooms"],
    permissions: [view, { id: "join", label: "Join Classes" }, create, edit, { id: "cancel", label: "Cancel Classes", critical: true }, assign, { id: "attendance", label: "Manage Attendance" }],
    defaultStatus: "enabled",
    defaultRolePermissions: {
      student: ["view", "join"],
      instructor: ["view", "join", "create", "edit", "attendance"],
      admin: ["view", "join", "create", "edit", "cancel", "assign", "attendance"],
    },
  },
  {
    key: "calendar",
    label: "Calendar",
    category: "Classroom",
    description: "Student, coach, and academy calendar views.",
    routes: ["/calendar"],
    permissions: [view, create, edit, approve],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view", "create"], instructor: ["view", "edit", "approve"], admin: all(view, create, edit, approve) },
  },
  {
    key: "availableTimes",
    label: "Available Times",
    category: "Classroom",
    description: "Coach availability setup and available time management.",
    routes: ["/availability"],
    apiPrefixes: ["/api/availability"],
    permissions: [view, create, edit, approve],
    defaultStatus: "enabled",
    defaultRolePermissions: { instructor: ["view", "edit", "approve"], admin: all(view, create, edit, approve) },
  },
  {
    key: "booking",
    label: "Booking",
    category: "Classroom",
    description: "Student booking flow and booking requests.",
    routes: ["/booking"],
    apiPrefixes: ["/api/bookings"],
    permissions: [view, create, approve],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view", "create"], instructor: ["view", "approve"], admin: all(view, create, approve) },
  },
  {
    key: "homework",
    label: "Homework",
    category: "Learning",
    description: "Homework lists, assignment creation, submissions, and review workflows.",
    routes: ["/homework", "/instructor/homework"],
    apiPrefixes: ["/api/homework"],
    permissions: [view, create, edit, del, assign],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view"], instructor: ["view", "create", "edit", "assign"], admin: all(view, create, edit, del, assign) },
  },
  {
    key: "homeworkTemplates",
    label: "Homework Templates",
    category: "Administration",
    description: "Homework template library, template upload, PGN-to-template generation, and template assignment.",
    routes: ["/admin/homework-templates"],
    apiPrefixes: ["/api/admin/assignment-templates"],
    permissions: [view, create, edit, del, assign],
    defaultStatus: "enabled",
    defaultRolePermissions: { instructor: ["view", "create", "edit", "assign"], admin: all(view, create, edit, del, assign) },
  },
  {
    key: "attendance",
    label: "Attendance",
    category: "Reports",
    description: "Attendance workspace and attendance updates.",
    routes: ["/attendance"],
    apiPrefixes: ["/api/attendance"],
    permissions: [view, edit, exportRecords],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view"], instructor: ["view"], admin: all(view, edit, exportRecords), "sub-admin": ["view", "edit"] },
  },
  {
    key: "askCoach",
    label: "Ask Coach",
    category: "Communication",
    description: "Student questions, coach replies, moderation, and batch messages.",
    routes: ["/ask-coach"],
    apiPrefixes: ["/api/ask-coach"],
    permissions: [view, create, { id: "moderate", label: "Moderate", critical: true }, share],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view", "create"], instructor: ["view", "create", "share"], admin: all(view, create, share, { id: "moderate", label: "Moderate" }) },
  },
  {
    key: "tournaments",
    label: "Tournaments",
    category: "Tournaments",
    description: "Tournament lists, creation, game play, pairings, results, and reports.",
    routes: ["/tournaments"],
    apiPrefixes: ["/api/tournaments"],
    permissions: [
      view,
      { id: "join", label: "Join Tournament" },
      create,
      edit,
      { id: "cancel", label: "Cancel Tournament", critical: true },
      { id: "participants", label: "Manage Participants" },
      { id: "pairings", label: "Generate Pairings" },
      { id: "results", label: "Correct Results" },
      exportRecords,
    ],
    defaultStatus: "enabled",
    defaultRolePermissions: {
      student: ["view", "join"],
      instructor: ["view"],
      admin: ["view", "join", "create", "edit", "cancel", "participants", "pairings", "results", "export"],
    },
  },
  {
    key: "leaderboards",
    label: "Leaderboards",
    category: "Tournaments",
    description: "Ranking, tournament standings, and student leaderboard views.",
    routes: ["/leaderboard"],
    permissions: [view, exportRecords],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view"], instructor: ["view"], admin: ["view", "export"] },
  },
  {
    key: "pgnLibrary",
    label: "PGN Library",
    category: "Training Tools",
    description: "PGN library, folders, viewers, sharing, and imports.",
    routes: ["/pgn"],
    apiPrefixes: ["/api/pgn"],
    permissions: [view, create, edit, del, share],
    defaultStatus: "enabled",
    defaultRolePermissions: { instructor: ["view", "create", "edit", "share"], admin: all(view, create, edit, del, share) },
  },
  {
    key: "analysisBoard",
    label: "Analysis Board",
    category: "Training Tools",
    description: "Chess analysis board and lesson analysis tools.",
    routes: ["/analysis"],
    permissions: [view, share],
    defaultStatus: "enabled",
    defaultRolePermissions: {
      student: ["view", "share"],
      instructor: ["view", "share"],
      admin: ["view", "share"],
      "sub-admin": ["view", "share"],
    },
  },
  {
    key: "playerAnalytics",
    label: "Player Analytics",
    category: "Training Tools",
    description: "Chess.com and Lichess account linking, game sync, player progress dashboards, and coach-scoped analytics.",
    routes: ["/chess-profile", "/instructor/students", "/admin/player-analytics"],
    apiPrefixes: ["/api/chess"],
    permissions: [
      view,
      { id: "view_assigned", label: "View Assigned Students" },
      { id: "view_all", label: "View All Students", critical: true },
      { id: "manage_accounts", label: "Manage Chess Accounts" },
      { id: "sync", label: "Trigger Sync" },
      { id: "games", label: "View Games" },
    ],
    defaultStatus: "enabled",
    defaultRolePermissions: {
      student: ["view", "manage_accounts", "sync", "games"],
      instructor: ["view", "view_assigned", "games"],
      admin: ["view", "view_all", "manage_accounts", "sync", "games"],
      "sub-admin": ["view", "view_all", "games"],
    },
  },
  {
    key: "tacticsTrainer",
    label: "Tactics Trainer",
    category: "Training Tools",
    description: "Tactics trainer and puzzle practice.",
    routes: ["/play/tactics-trainer", "/tactics-trainer"],
    apiPrefixes: ["/api/tactics-trainer"],
    permissions: [view, { id: "practice", label: "Practice" }],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view", "practice"], admin: ["view", "practice"] },
  },
  {
    key: "kingHunt",
    label: "King Hunt",
    category: "Training Tools",
    description: "King Hunt practice mode.",
    routes: ["/play/king-hunt", "/king-hunt"],
    permissions: [view, { id: "practice", label: "Practice" }],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view", "practice"], admin: ["view", "practice"] },
  },
  {
    key: "squareTrainer",
    label: "Square Trainer",
    category: "Training Tools",
    description: "Square trainer practice mode.",
    routes: ["/play/square-trainer", "/square-trainer"],
    apiPrefixes: ["/api/square-trainer"],
    permissions: [view, { id: "practice", label: "Practice" }],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view", "practice"], admin: ["view", "practice"] },
  },
  {
    key: "playVsComputer",
    label: "Play vs Computer",
    category: "Training Tools",
    description: "Computer opponent practice and rewards.",
    routes: ["/play/computer"],
    apiPrefixes: ["/api/play/computer"],
    permissions: [view, { id: "play", label: "Play" }],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view", "play"], admin: ["view", "play"] },
  },
  {
    key: "learnChess",
    label: "Learn Chess",
    category: "Training Tools",
    description: "Structured learn-to-play curriculum, lesson progress, and guided chess practice.",
    routes: ["/learn"],
    apiPrefixes: ["/api/learn"],
    permissions: [view, { id: "practice", label: "Practice" }, create, edit, assign, manage],
    defaultStatus: "enabled",
    defaultRolePermissions: {
      student: ["view", "practice"],
      instructor: ["view", "assign"],
      admin: ["view", "practice", "create", "edit", "assign", "manage"],
      "sub-admin": ["view", "practice"],
    },
  },
  {
    key: "fees",
    label: "Fees Management",
    category: "Payments",
    description: "Parent access for fee APIs, payment webhooks, and shared billing operations.",
    routes: ["/fees/reminders"],
    apiPrefixes: ["/api/fees", "/api/payments"],
    permissions: [view, { id: "invoice", label: "Create Invoice" }, edit, { id: "payment", label: "Record Payment" }, { id: "credit", label: "Issue Credit", critical: true }, exportRecords],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view"], admin: ["view", "invoice", "edit", "payment", "credit", "export"] },
  },
  {
    key: "feeDashboard",
    label: "Fee Dashboard",
    category: "Payments",
    description: "Main fee dashboard and billing overview.",
    routes: ["/fees"],
    permissions: [view],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view"], admin: ["view"] },
  },
  {
    key: "feePlans",
    label: "Fee Plans",
    category: "Payments",
    description: "Fee plan setup, pricing rules, and plan edits.",
    routes: ["/fees/fee-plans"],
    permissions: [view, create, edit, del],
    defaultStatus: "enabled",
    defaultRolePermissions: { admin: all(view, create, edit, del) },
  },
  {
    key: "studentFees",
    label: "Student Fees",
    category: "Payments",
    description: "Student fee records, manual credits, payments, and account balances.",
    routes: ["/fees/student-fees", "/fees/credit-history"],
    permissions: [view, edit, { id: "payment", label: "Record Payment" }, { id: "credit", label: "Issue Credit", critical: true }],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view"], admin: ["view", "edit", "payment", "credit"] },
  },
  {
    key: "creditMonitoring",
    label: "Credit Monitoring",
    category: "Payments",
    description: "Credit usage monitoring and low-credit operational views.",
    routes: ["/fees/credit-monitoring"],
    permissions: [view, { id: "credit", label: "Issue Credit", critical: true }, exportRecords],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view"], admin: ["view", "credit", "export"] },
  },
  {
    key: "invoices",
    label: "Invoices",
    category: "Payments",
    description: "Student and admin invoice lists, invoice review, and invoice PDF access.",
    routes: ["/fees/invoices", "/invoices"],
    permissions: [view, { id: "invoice", label: "Create Invoice" }, edit, { id: "payment", label: "Record Payment" }, { id: "credit", label: "Issue Credit", critical: true }, exportRecords],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view"], admin: ["view", "invoice", "edit", "payment", "credit", "export"] },
  },
  {
    key: "feeReports",
    label: "Fee Reports",
    category: "Payments",
    description: "Fee reports, exports, and finance summaries.",
    routes: ["/fees/reports"],
    permissions: [view, exportRecords],
    defaultStatus: "enabled",
    defaultRolePermissions: { admin: ["view", "export"] },
  },
  {
    key: "notifications",
    label: "Notifications",
    category: "Communication",
    description: "Portal notifications and notification management.",
    routes: ["/admin/notifications"],
    apiPrefixes: ["/api/notifications"],
    permissions: [view, create, manage],
    defaultStatus: "enabled",
    defaultRolePermissions: { student: ["view"], instructor: ["view"], admin: all(view, create, manage) },
  },
  {
    key: "whatsapp",
    label: "WhatsApp",
    category: "Communication",
    description: "WhatsApp Business API inbox, active 24-hour conversations, template sends, replies, and Meta webhooks.",
    routes: ["/admin/whatsapp"],
    apiPrefixes: ["/api/admin/whatsapp"],
    permissions: [view, create, manage],
    defaultStatus: "enabled",
    defaultRolePermissions: { admin: all(view, create, manage), "sub-admin": ["view", "create"] },
  },
  {
    key: "userManagement",
    label: "Student, Coach, and Admin Management",
    category: "Administration",
    description: "User directory, account creation, role changes, activation, and password resets.",
    routes: ["/admin/users"],
    apiPrefixes: ["/api/admin/users"],
    permissions: [view, create, edit, del, manage],
    defaultStatus: "enabled",
    defaultRolePermissions: { admin: all(view, create, edit, del, manage) },
  },
  {
    key: "onboarding",
    label: "Onboarding",
    category: "Administration",
    description: "Demo student approvals, coach applications, and onboarding decisions.",
    routes: ["/admin/onboarding", "/admin/demo-center", "/admin/coach-applications"],
    permissions: [view, approve, edit],
    defaultStatus: "enabled",
    defaultRolePermissions: { admin: all(view, approve, edit) },
  },
  {
    key: "courseManagement",
    label: "Course Management",
    category: "Administration",
    description: "Courses, batches, levels, branches, and enrolment structure.",
    routes: ["/admin/courses"],
    apiPrefixes: ["/api/admin/courses", "/api/admin/batches"],
    permissions: [view, create, edit, del, assign],
    defaultStatus: "enabled",
    defaultRolePermissions: { admin: all(view, create, edit, del, assign) },
  },
  {
    key: "achievements",
    label: "Achievement Management",
    category: "Administration",
    description: "Student achievement records, images, featured homepage placement, public visibility, and ordering.",
    routes: ["/admin/achievements"],
    apiPrefixes: ["/api/admin/achievements"],
    permissions: [view, create, edit, del, manage],
    defaultStatus: "enabled",
    defaultRolePermissions: { admin: all(view, create, edit, del, manage) },
  },
  {
    key: "reports",
    label: "Reports and Progress",
    category: "Reports",
    description: "Parent access for reports and operational history.",
    routes: [],
    apiPrefixes: ["/api/admin/reports", "/api/admin/activity-tracker"],
    permissions: [view, exportRecords, manage],
    defaultStatus: "enabled",
    defaultRolePermissions: { admin: all(view, exportRecords, manage) },
  },
  {
    key: "activityTracker",
    label: "Activity Tracker",
    category: "Reports",
    description: "Admin activity tracker, audit history, and activity exports.",
    routes: ["/admin/activity-tracker"],
    permissions: [view, exportRecords],
    defaultStatus: "enabled",
    defaultRolePermissions: { admin: ["view", "export"] },
  },
  {
    key: "reportsCenter",
    label: "Reports Center",
    category: "Reports",
    description: "Admin reports center and academy operational reports.",
    routes: ["/admin/reports"],
    permissions: [view, exportRecords, manage],
    defaultStatus: "enabled",
    defaultRolePermissions: { admin: all(view, exportRecords, manage) },
  },
  {
    key: "announcements",
    label: "Announcements",
    category: "Communication",
    description: "Academy announcements and targeted communication.",
    routes: ["/admin/announcements"],
    apiPrefixes: ["/api/admin/announcements"],
    permissions: [view, create, edit, del, share],
    defaultStatus: "enabled",
    defaultRolePermissions: { admin: all(view, create, edit, del, share) },
  },
  {
    key: "academySettings",
    label: "Academy Setup",
    category: "Settings",
    description: "Branding, invoice identity, GST settings, and academy defaults.",
    routes: ["/admin/settings"],
    apiPrefixes: ["/api/branding", "/api/admin/google-business", "/api/admin/google-reviews"],
    permissions: [view, edit, manage],
    defaultStatus: "enabled",
    defaultRolePermissions: { admin: all(view, edit, manage) },
  },
  {
    key: "accountSettings",
    label: "Account Settings",
    category: "Settings",
    description: "Personal profile image, limited profile details, password changes, and password reset requests.",
    routes: ["/profile"],
    apiPrefixes: ["/api/profile"],
    permissions: [view, edit, { id: "security", label: "Password & Security" }],
    defaultStatus: "enabled",
    defaultRolePermissions: {
      student: ["view", "edit", "security"],
      instructor: ["view", "edit", "security"],
      admin: ["view", "edit", "security"],
      "sub-admin": ["view", "edit", "security"],
    },
  },
  {
    key: "featureAccess",
    label: "Feature Access & Permissions",
    category: "Settings",
    description: "Central controls for feature flags, role permissions, pilot access, templates, and audit history.",
    routes: ["/admin/feature-access"],
    apiPrefixes: ["/api/admin/feature-access"],
    permissions: [view, edit, manage, full],
    defaultStatus: "enabled",
    defaultRolePermissions: { admin: all(view, edit, manage, full) },
  },
  {
    key: "certificates",
    label: "Certificates",
    category: "Learning",
    description: "Certificate generation and student achievement records.",
    routes: ["/certificates"],
    permissions: [view, create, share],
  },
  {
    key: "activityCentre",
    label: "Activity Centre",
    category: "Learning",
    description: "Student activity centre and practice challenges.",
    routes: ["/activity-centre"],
    permissions: [view, create, edit],
  },
];

export const FEATURE_CATEGORIES = Array.from(new Set(FEATURE_DEFINITIONS.map((feature) => feature.category)));

export function findFeatureByPath(pathname: string) {
  const normalized = pathname === "/" ? "/" : pathname.replace(/\/$/, "");
  return FEATURE_DEFINITIONS
    .flatMap((feature) => feature.routes.map((route) => ({ feature, route })))
    .sort((a, b) => b.route.length - a.route.length)
    .find(({ route }) => normalized === route || normalized.startsWith(`${route}/`))?.feature;
}

export function findFeatureByApiPath(pathname: string) {
  const normalized = pathname === "/" ? "/" : pathname.replace(/\/$/, "");
  return FEATURE_DEFINITIONS
    .flatMap((feature) => (feature.apiPrefixes || []).map((route) => ({ feature, route })))
    .sort((a, b) => b.route.length - a.route.length)
    .find(({ route }) => normalized === route || normalized.startsWith(`${route}/`))?.feature;
}
