import { Schema, model, models, type InferSchemaType } from "mongoose";

const TournamentSchema = new Schema(
  {
    name: { type: String, required: true, index: true },
    description: String,
    type: { type: String, enum: ["swiss", "arena"], required: true, index: true },
    status: { type: String, enum: ["draft", "created", "registration_open", "starting_soon", "upcoming", "live", "playing", "completed", "finished", "cancelled"], default: "upcoming", index: true },
    arenaDurationMinutes: Number,
    rounds: Number,
    timeControlMinutes: { type: Number, required: true },
    incrementSeconds: { type: Number, default: 0 },
    breakBetweenRoundsMinutes: { type: Number, default: 0 },
    rated: { type: Boolean, default: false },
    allowBerserk: { type: Boolean, default: false },
    arenaStreaks: { type: Boolean, default: true },
    earlyDrawMoveLimit: { type: Number, default: 10 },
    drawStreakLimit: { type: Number, default: 2 },
    chatEnabled: { type: Boolean, default: false },
    lateJoiningAllowed: { type: Boolean, default: true },
    entryRestrictions: { type: String, default: "" },
    pausedByAdmin: { type: Boolean, default: false, index: true },
    pairingLock: {
      token: String,
      expiresAt: Date,
    },
    startAt: { type: Date, required: true, index: true },
    repeat: {
      enabled: { type: Boolean, default: false },
      untilDate: Date,
      selectedDays: [Number],
      repeatCount: Number,
      daily: { type: Boolean, default: false },
    },
    startingPosition: {
      type: { type: String, enum: ["normal", "custom"], default: "normal" },
      fen: String,
    },
    access: {
      allActiveStudents: { type: Boolean, default: false },
      includeCoaches: { type: Boolean, default: false },
      includeInactiveStudents: { type: Boolean, default: false },
      batches: [{ type: Schema.Types.ObjectId, ref: "Batch", index: true }],
      courses: [{ type: Schema.Types.ObjectId, ref: "Course", index: true }],
      levels: [{ type: String, index: true }],
      users: [{ type: Schema.Types.ObjectId, ref: "User", index: true }],
    },
    participants: [{ type: Schema.Types.ObjectId, ref: "User", index: true }],
    participantStates: [
      {
        playerKey: { type: String, required: true, index: true },
        status: { type: String, enum: ["joined", "queued", "playing", "paused", "withdrawn"], default: "joined", index: true },
        joinedAt: { type: Date, default: Date.now },
        queuedAt: Date,
        pausedAt: Date,
        lastSeenAt: Date,
      },
    ],
    externalInvite: {
      enabled: { type: Boolean, default: false, index: true },
      token: { type: String, index: true },
      password: String,
      entryCode: String,
      accessMode: { type: String, enum: ["public", "private", "password", "entry_code"], default: "password" },
      createdAt: Date,
      expiresAt: Date,
    },
    externalParticipants: [{
      username: { type: String, required: true },
      displayName: String,
      email: String,
      entryCode: String,
      joinedAt: { type: Date, default: Date.now },
    }],
    chatMessages: [
      {
        senderKey: String,
        senderName: String,
        message: String,
        createdAt: { type: Date, default: Date.now },
        hidden: { type: Boolean, default: false },
      },
    ],
    currentRound: { type: Number, default: 0 },
    initialParticipantKeys: [{ type: String }],
    startedAt: Date,
    endedAt: Date,
    arenaEndsAt: Date,
    standings: [
      {
        playerKey: { type: String, required: true, index: true },
        user: { type: Schema.Types.ObjectId, ref: "User", index: true },
        externalUsername: String,
        displayName: String,
        rating: { type: Number, default: 0 },
        points: { type: Number, default: 0 },
        wins: { type: Number, default: 0 },
        draws: { type: Number, default: 0 },
        losses: { type: Number, default: 0 },
        byes: { type: Number, default: 0 },
        gamesPlayed: { type: Number, default: 0 },
        buchholz: { type: Number, default: 0 },
        streak: { type: Number, default: 0 },
        lastColor: { type: String, enum: ["white", "black", ""], default: "" },
        scoreHistory: [{ type: Number, default: 0 }],
        recentResults: [{ type: String }],
      },
    ],
    roundsData: [
      {
        roundNumber: { type: Number, required: true },
        status: { type: String, enum: ["pending", "live", "completed"], default: "pending" },
        startedAt: Date,
        endedAt: Date,
        pairings: [
          {
            gameId: { type: Schema.Types.ObjectId, ref: "TournamentGame" },
            tableNumber: Number,
            whiteKey: String,
            blackKey: String,
            whiteName: String,
            blackName: String,
            result: { type: String, default: "*" },
            status: { type: String, enum: ["pending", "live", "completed", "aborted"], default: "pending" },
          },
        ],
      },
    ],
    finalSnapshot: {
      standings: [{ type: Schema.Types.Mixed }],
      podium: [{ type: Schema.Types.Mixed }],
      totalGames: { type: Number, default: 0 },
      completedGames: { type: Number, default: 0 },
      generatedAt: Date,
    },
    adminActions: [
      {
        actor: { type: Schema.Types.ObjectId, ref: "User", index: true },
        action: { type: String, required: true },
        note: String,
        metadata: { type: Schema.Types.Mixed },
        createdAt: { type: Date, default: Date.now },
      },
    ],
    createdBy: { type: Schema.Types.ObjectId, ref: "User", required: true, index: true },
    parentTournament: { type: Schema.Types.ObjectId, ref: "Tournament", index: true },
  },
  { timestamps: true }
);

export type TournamentDoc = InferSchemaType<typeof TournamentSchema> & { _id: any };
export const Tournament = models.Tournament || model("Tournament", TournamentSchema);
